# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\quiz.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(649, 521)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background: #000000;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: #fff;\n"
"    font-size: 16px;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.button_h = QtWidgets.QPushButton(self.centralwidget)
        self.button_h.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.button_h.setFont(font)
        self.button_h.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_h.setStyleSheet("QPushButton {\n"
"    background-color: #555;\n"
"    border: 2px solid #666;\n"
"    border-radius: 20;\n"
"    color: #eee;\n"
"    height: 40px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #1c7fe8;\n"
"    border-color: #1c7fe8;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #000;\n"
"    border-color: #000;\n"
"    color: #000;\n"
"}")
        self.button_h.setObjectName("button_h")
        self.gridLayout.addWidget(self.button_h, 5, 1, 1, 1)
        self.button_f = QtWidgets.QPushButton(self.centralwidget)
        self.button_f.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.button_f.setFont(font)
        self.button_f.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_f.setStyleSheet("QPushButton {\n"
"    background-color: #555;\n"
"    border: 2px solid #666;\n"
"    border-radius: 20;\n"
"    color: #eee;\n"
"    height: 40px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #1c7fe8;\n"
"    border-color: #1c7fe8;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #000;\n"
"    border-color: #000;\n"
"    color: #000;\n"
"}")
        self.button_f.setObjectName("button_f")
        self.gridLayout.addWidget(self.button_f, 4, 1, 1, 1)
        self.button_b = QtWidgets.QPushButton(self.centralwidget)
        self.button_b.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.button_b.setFont(font)
        self.button_b.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_b.setStyleSheet("QPushButton {\n"
"    background-color: #555;\n"
"    border: 2px solid #666;\n"
"    border-radius: 20;\n"
"    color: #eee;\n"
"    height: 40px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #1c7fe8;\n"
"    border-color: #1c7fe8;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #000;\n"
"    border-color: #000;\n"
"    color: #000;\n"
"}")
        self.button_b.setCheckable(False)
        self.button_b.setObjectName("button_b")
        self.gridLayout.addWidget(self.button_b, 0, 1, 1, 1)
        self.button_a = QtWidgets.QPushButton(self.centralwidget)
        self.button_a.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.button_a.setFont(font)
        self.button_a.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_a.setStyleSheet("QPushButton {\n"
"    background-color: #555;\n"
"    border: 2px solid #666;\n"
"    border-radius: 20;\n"
"    color: #eee;\n"
"    height: 40px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #1c7fe8;\n"
"    border-color: #1c7fe8;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #000;\n"
"    border-color: #000;\n"
"    color: #000;\n"
"}")
        self.button_a.setObjectName("button_a")
        self.gridLayout.addWidget(self.button_a, 0, 0, 1, 1)
        self.button_d = QtWidgets.QPushButton(self.centralwidget)
        self.button_d.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.button_d.setFont(font)
        self.button_d.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_d.setStyleSheet("QPushButton {\n"
"    background-color: #555;\n"
"    border: 2px solid #666;\n"
"    border-radius: 20;\n"
"    color: #eee;\n"
"    height: 40px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #1c7fe8;\n"
"    border-color: #1c7fe8;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #000;\n"
"    border-color: #000;\n"
"    color: #000;\n"
"}")
        self.button_d.setObjectName("button_d")
        self.gridLayout.addWidget(self.button_d, 3, 1, 1, 1)
        self.button_g = QtWidgets.QPushButton(self.centralwidget)
        self.button_g.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.button_g.setFont(font)
        self.button_g.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_g.setStyleSheet("QPushButton {\n"
"    background-color: #555;\n"
"    border: 2px solid #666;\n"
"    border-radius: 20;\n"
"    color: #eee;\n"
"    height: 40px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #1c7fe8;\n"
"    border-color: #1c7fe8;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #000;\n"
"    border-color: #000;\n"
"    color: #000;\n"
"}")
        self.button_g.setObjectName("button_g")
        self.gridLayout.addWidget(self.button_g, 5, 0, 1, 1)
        self.button_c = QtWidgets.QPushButton(self.centralwidget)
        self.button_c.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.button_c.setFont(font)
        self.button_c.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_c.setStyleSheet("QPushButton {\n"
"    background-color: #555;\n"
"    border: 2px solid #666;\n"
"    border-radius: 20;\n"
"    color: #eee;\n"
"    height: 40px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #1c7fe8;\n"
"    border-color: #1c7fe8;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #000;\n"
"    border-color: #000;\n"
"    color: #000;\n"
"}")
        self.button_c.setObjectName("button_c")
        self.gridLayout.addWidget(self.button_c, 3, 0, 1, 1)
        self.button_e = QtWidgets.QPushButton(self.centralwidget)
        self.button_e.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.button_e.setFont(font)
        self.button_e.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_e.setStyleSheet("QPushButton {\n"
"    background-color: #555;\n"
"    border: 2px solid #666;\n"
"    border-radius: 20;\n"
"    color: #eee;\n"
"    height: 40px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #1c7fe8;\n"
"    border-color: #1c7fe8;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #000;\n"
"    border-color: #000;\n"
"    color: #000;\n"
"}")
        self.button_e.setObjectName("button_e")
        self.gridLayout.addWidget(self.button_e, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.replay = QtWidgets.QPushButton(self.centralwidget)
        self.replay.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.replay.setFont(font)
        self.replay.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.replay.setStyleSheet("QPushButton {\n"
"    background-color: rgb(15, 151, 255);\n"
"    border: 2px solid rgb(15, 151, 255);\n"
"    border-radius: 20;\n"
"    color: #eee;\n"
"    height: 40px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(12, 129, 217);\n"
"    border-color: rgb(12, 129, 217);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(12, 129, 217);\n"
"    border-color: rgb(12, 129, 217);\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #000;\n"
"    border-color: #000;\n"
"    color: #000;\n"
"}")
        self.replay.setObjectName("replay")
        self.horizontalLayout.addWidget(self.replay)
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.exit.setFont(font)
        self.exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 114, 14);\n"
"    border: 2px solid rgb(240, 100, 12);\n"
"    border-radius: 20;\n"
"    color: #eee;\n"
"    height: 40px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(235, 95, 8);\n"
"    border-color: rgb(235, 95, 8);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(235, 95, 8);\n"
"    border-color: rgb(235, 95, 8);\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #000;\n"
"    border-color: #000;\n"
"    color: #000;\n"
"}")
        self.exit.setObjectName("exit")
        self.horizontalLayout.addWidget(self.exit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "This is an exemple of a questions... is it?"))
        self.button_h.setText(_translate("MainWindow", "PushButton"))
        self.button_f.setText(_translate("MainWindow", "PushButton"))
        self.button_b.setText(_translate("MainWindow", "PushButton"))
        self.button_a.setText(_translate("MainWindow", "PushButton"))
        self.button_d.setText(_translate("MainWindow", "PushButton"))
        self.button_g.setText(_translate("MainWindow", "PushButton"))
        self.button_c.setText(_translate("MainWindow", "PushButton"))
        self.button_e.setText(_translate("MainWindow", "PushButton"))
        self.replay.setText(_translate("MainWindow", "Replay"))
        self.exit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
